---
- name: Create env file for Node app
  template:
    src: .env.tpl
    dest: "{{ repo_dir }}/{{ subfolder }}/.env"

- name: Install PM2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Build app and run db migrations
  command: "{{ item }}"
  register: node_build
  with_items:
    - npm ci
    - npx prisma db push
    - npx prisma migrate deploy
  args:
    chdir: "{{ repo_dir }}/{{ subfolder }}"

- name: Delete PM2 process if exists
  when: node_build.changed
  ignore_errors: True
  command: "{{ item }}"
  with_items:
    - pm2 delete src/server.js --name backend
  args:
    chdir: "{{ repo_dir }}/{{ subfolder }}"

- name: Start app with PM2
  command: "{{ item }}"
  with_items:
    - pm2 start src/server.js --name backend
  args:
    chdir: "{{ repo_dir }}/{{ subfolder }}"
