---
- name: Create env file for Node app
  template:
    src: .env.tpl
    dest: "{{ repo_dir }}/{{ subfolder }}/.env"

- name: Install PM2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Build app and run db migrations
  command: "{{ item }}"
  register: node_build
  with_items:
    - npm ci
    - npm run db:migrate
  args:
    chdir: "{{ repo_dir }}/{{ subfolder }}"

- name: Delete PM2 process if exists
  when: node_build.changed
  ignore_errors: True
  command: "{{ item }}"
  with_items:
    - pm2 delete src/server.js --name backend
  args:
    chdir: "{{ repo_dir }}/{{ subfolder }}"

- name: Start app with PM2
  command: "{{ item }}"
  with_items:
    - pm2 start src/server.js --name backend
  args:
    chdir: "{{ repo_dir }}/{{ subfolder }}"

# handlers:
# - name: start PM2
#   command:


# - name: Copy build folder to nginx vhost
#   become: yes
#   copy:
#     src: "{{ repo_dir }}/{{ subfolder }}/build/"
#     dest: "{{ nginx_vhost_dir }}"
#     mode: "0644"
#     remote_src: yes
#     directory_mode: yes
#   notify: restart nginx

# - name: Create symlink nginx vhost
#   become: yes
#   file:
#     src={{ nginx_sites }}/{{ app_name }}.conf
#     dest=/etc/nginx/sites-enabled/{{ app_name }}.conf
#     state=link
#   notify: restart nginx

# - name: Recursively remove directory
#   file:
#     path: "{{ repo_dir }}"
#     state: absent

# handlers:
# - name: restart nginx
#   become: yes
#   service:
#     name: nginx
#     state: restarted